<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-EP26A9T0" failures="0" tests="15" name="testscripts.QaLegend_userstest" time="0.025" errors="3" timestamp="2025-03-11T17:25:47 IST" skipped="12">
  <testcase classname="testscripts.QaLegend_userstest" name="createaUser" time="0.010">
    <skipped/>
  </testcase> <!-- createaUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="createaUser" time="0.001">
    <skipped/>
  </testcase> <!-- createaUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="createaUser" time="0.002">
    <error message="Cannot invoke &quot;java.util.Properties.getProperty(String)&quot; because &quot;this.prop&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.prop" is null
at testscripts.QaLegend_userstest.createaUser(QaLegend_userstest.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </error>
  </testcase> <!-- createaUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="createaUser" time="0.002">
    <skipped/>
  </testcase> <!-- createaUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="createaUser" time="0.001">
    <skipped/>
  </testcase> <!-- createaUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="deleteUser" time="0.002">
    <skipped/>
  </testcase> <!-- deleteUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="deleteUser" time="0.002">
    <skipped/>
  </testcase> <!-- deleteUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="deleteUser" time="0.001">
    <error message="Cannot invoke &quot;java.util.Properties.getProperty(String)&quot; because &quot;this.prop&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.prop" is null
at testscripts.QaLegend_userstest.deleteUser(QaLegend_userstest.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </error>
  </testcase> <!-- deleteUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="deleteUser" time="0.000">
    <skipped/>
  </testcase> <!-- deleteUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="deleteUser" time="0.001">
    <skipped/>
  </testcase> <!-- deleteUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="editUser" time="0.001">
    <skipped/>
  </testcase> <!-- editUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="editUser" time="0.000">
    <skipped/>
  </testcase> <!-- editUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="editUser" time="0.001">
    <error message="Cannot invoke &quot;java.util.Properties.getProperty(String)&quot; because &quot;this.prop&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.prop" is null
at testscripts.QaLegend_userstest.editUser(QaLegend_userstest.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </error>
  </testcase> <!-- editUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="editUser" time="0.001">
    <skipped/>
  </testcase> <!-- editUser -->
  <system-out/>
  <testcase classname="testscripts.QaLegend_userstest" name="editUser" time="0.000">
    <skipped/>
  </testcase> <!-- editUser -->
  <system-out/>
</testsuite> <!-- testscripts.QaLegend_userstest -->
